### ISSUE TITLE
Does not accept block parameters on Ruby 2.2.2

### ISSUE THREAD

**Issue by jarmo** [ngty/serializable_proc#10]
I'm using the following Ruby on Windows:

    ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]

The following code will throw an error:

```ruby
puts (SerializableProc.new {|i| i + 2}).call(1)
```

Error:
```
:in `block in eval!': undefined method `+' for nil:NilClass (NoMethodError)
        from C:/bin/Ruby22/lib/ruby/gems/2.2.0/gems/serializable_proc-0.4.1/lib/serializable_proc.rb:222:in `call'
        from C:/bin/Ruby22/lib/ruby/gems/2.2.0/gems/serializable_proc-0.4.1/lib/serializable_proc.rb:222:in `call'
```

Block variable `i` is `nil` although it is given as an argument to `#call`.

If I change the code to like this:
```ruby
puts (SerializableProc.new {|i| 2}).call(1)
```

Then it outputs `2` as expected.

Any ideas what might be wrong or is the problem in Ruby 2.2?

**Comment by jarmo** [comment]
I tried it with `ruby 1.9.3p448 (2013-06-27) [i386-mingw32]` and are seeing exactly the same problem.

**Comment by ngty** [comment]
Hey Jarmo, sorry for the delay in reply. 

Since project is no longer maintained, i'm really sorry for the inconvenience caused.
